/**
 * Class icons.
 *
 * The map is generated by tools/gen_icons.py alongside the SVGs, so a glyph and its
 * mapping can never drift apart. Lookup order matches the order the plugin sends tags
 * in: exact class first, then base classes most specific to least, then a fallback.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

import { RbxNode } from './protocol';

interface IconMap {
  fallback: string;
  /** Any top-level service the map has no glyph of its own for. */
  serviceFallback: string;
  disabledOverlay: string;
  byClass: Record<string, string>;
  byTag: Record<string, string>;
}

export class IconResolver {
  private map: IconMap;
  private dir: string;
  private cache = new Map<string, vscode.Uri>();

  constructor(extensionPath: string) {
    this.dir = path.join(extensionPath, 'media', 'icons');
    const mapPath = path.join(extensionPath, 'media', 'icon-map.json');
    try {
      this.map = JSON.parse(fs.readFileSync(mapPath, 'utf8')) as IconMap;
    } catch {
      // Losing the map should degrade to plain rows, not break the whole tree.
      this.map = {
        fallback: 'instance',
        serviceFallback: 'service',
        disabledOverlay: 'script-disabled',
        byClass: {},
        byTag: {},
      };
    }
  }

  /** The glyph name for a node, ignoring whether the file exists. */
  glyphFor(node: RbxNode): string {
    if (node.flags?.disabled) {
      return this.map.disabledOverlay;
    }
    const exact = this.map.byClass[node.className];
    if (exact) {
      return exact;
    }
    for (const tag of node.tags ?? []) {
      const byTag = this.map.byTag[tag];
      if (byTag) {
        return byTag;
      }
    }
    // A service the map has never heard of still deserves better than the generic dot,
    // and this is why new Roblox services need no map entry at all.
    if (node.flags?.service) {
      return this.map.serviceFallback;
    }
    return this.map.fallback;
  }

  /**
   * Resolves to a file URI VS Code can render. Returns a ThemeIcon instead if the SVG
   * is missing, so a half-built checkout still shows a usable tree.
   */
  iconFor(node: RbxNode): vscode.Uri | vscode.ThemeIcon {
    const glyph = this.glyphFor(node);
    const cached = this.cache.get(glyph);
    if (cached) {
      return cached;
    }
    const file = path.join(this.dir, `${glyph}.svg`);
    if (!fs.existsSync(file)) {
      return new vscode.ThemeIcon('symbol-misc');
    }
    const uri = vscode.Uri.file(file);
    this.cache.set(glyph, uri);
    return uri;
  }
}
